### ISSUE TITLE
Include fontpaths option in embed example

### ISSUE THREAD

**Issue by mihaic** [wch/fontcm#1]
Thanks for creating extrafont and fontcm. They make my life much easier. I just started using them and I could not reproduce the example in the README. gs would not find the font files installed by fontcm. I'm doing this instead:
embedFonts("plot.pdf", fontpaths=paste0(.libPaths(), "/fontcm/fonts/outlines/"))

**Comment by wch** [comment]
I think that's because of an oversight in the readme... Can you try running `loadfonts()` before creating the plot and embedding fonts? I think that should fix it. I've also updated the example.

**Comment by mihaic** [comment]
It's my fault, I was using embedFonts instead of embed_fonts, sorry. I now read the source code for embed_fonts and it's basically what I was trying to do, but more generic.

**Comment by wch** [comment]
I'm glad it works for you!
