### ISSUE TITLE
PNG output?

### ISSUE THREAD

**Issue by wmayner** [wch/fontcm#4]
Hi,

Thanks for this! Is there support for PNG output, or does it only work with PDFs? I'm using `ggplot2` with the `png` device, and it can't seem to find the font family `"CM Roman"`.

I did the following before trying to generate the PNG:

```
library(extrafont)
font_install('fontcm')
loadfonts()
```

And `fonts()` does show the various CM variants.

**Comment by wch** [comment]
Sorry, I don't think it's possible to do direct PNG output with the extrafont package. But I believe you should be able to install Computer Modern at the OS level and then use it for PNG output.

**Comment by wmayner** [comment]
Gotcha. Thanks!
